apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: postgres-int
  name: postgres-int
spec:
  replicas: 1
  selector:
    app: postgres-int
    deploymentconfig: postgres-int
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: postgres-int
        deploymentconfig: postgres-int
    spec:
      containers:
      - image: postgres
        name: postgres
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRESQL_DATABASE
          value: dojo
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: slabdojo-db
              key: user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: slabdojo-db
              key: password
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: pg-data
      volumes:
      - name: pg-data
        persistentVolumeClaim:
          claimName: pg-data-int
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - postgres
      from:
        kind: ImageStreamTag
        name: postgres:latest
    type: ImageChange
