apiVersion: v1
kind: Service
metadata:
  labels:
    app: teamdojo-int
  name: teamdojo-int
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: teamdojo-int